from typing import Sequence

MatID = int

MESH_INVALID: int
MESH_TRI: int
MESH_QUAD: int
MESH_TRIQUAD: int
MESH_QUADRATIC_TRI: int
MESH_QUADRATIC_QUAD: int
MESH_QUADRATIC_TRIQUAD: int

def initialize() -> None: ...
def finalize() -> None: ...

def overlay_coarse_grid(model: "MPACTModel", moderator: "Material") -> None: ...

def set_mesh_field_from_knudsen_number(
    model: "MPACTModel",
    dim: int,
    target_kn: float,
    fuel_mfp_threshold: float = -1.0,
    fuel_mfp_scale: float = -1.0,
    abs_mfp_threshold: float = -1.0,
    abs_mfp_scale: float = -1.0,
) -> None: ...

def set_global_mesh_size(size: float) -> None: ...

def generate_mesh(mesh_type: int) -> None: ...

def add_cylindrical_pin_lattice_2d(
    lattice_ids: Sequence[Sequence[int]],
    xy_extents: Sequence[Sequence[float]],
    pin_radii: Sequence[Sequence[float]],
    pin_materials: Sequence[Sequence["Material"]],
    origin_x: float,
    origin_y: float,
) -> None: ...

def get_c5g7_materials() -> list["Material"]: ...

def size_of_int() -> int: ...
def size_of_float() -> int: ...


class Color:
    def __init__(self, r: int = 0, g: int = 0, b: int = 0, a: int = 255) -> None: ...
    @property
    def r(self) -> int: ...
    @r.setter
    def r(self, value: int) -> None: ...
    @property
    def g(self) -> int: ...
    @g.setter
    def g(self, value: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, value: int) -> None: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, value: int) -> None: ...


class Material:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def color(self) -> Color: ...
    @color.setter
    def color(self, value: Color) -> None: ...
    @property
    def temperature(self) -> float: ...
    @temperature.setter
    def temperature(self, value: float) -> None: ...
    @property
    def density(self) -> float: ...
    @density.setter
    def density(self, value: float) -> None: ...
    def num_nuclides(self) -> int: ...
    def num_density(self, i: int) -> float: ...
    def zaid(self, i: int) -> int: ...


class MPACTModel:
    def __init__(self) -> None: ...
    def add_material(self, material: Material) -> None: ...
    def add_coarse_grid(
        self,
        x_extent: float,
        y_extent: float,
        nx: int,
        ny: int,
    ) -> None: ...
    def add_cylindrical_pin_mesh(
        self,
        pitch: float,
        radii: Sequence[float],
        rings: Sequence[int],
        num_azi: int,
        mesh_order: int,
    ) -> int: ...
    def add_rectangular_pin_mesh(
        self,
        xy_extents: Sequence[float],
        nx: int,
        ny: int,
    ) -> int: ...
    def add_coarse_cell(
        self,
        xy_extents: Sequence[float],
        mesh_type: int,
        mesh_id: int,
        mat_ids: Sequence[MatID],
    ) -> None: ...
    def add_rtm(
        self,
        ids: Sequence[Sequence[int]],
    ) -> None: ...
    def add_lattice(
        self,
        ids: Sequence[Sequence[int]],
    ) -> None: ...
    def add_assembly(
        self,
        lattice_ids: Sequence[int],
        z_slices: Sequence[float],
    ) -> None: ...
    def add_core(
        self,
        ids: Sequence[Sequence[int]],
    ) -> None: ...
    def write(self, path: str) -> None: ...
    def export_model(
        self,
        inp_path: str,
        xdmf_path: str,
        write_knudsen_data: bool = True,
    ) -> None: ...
    def close(self) -> None: ...